local handshake = require("neovim-pi.handshake")
local rpc = require("neovim-pi.rpc")

describe("neovim-pi.handshake", function()
  before_each(function()
    rpc.clear_channel()
  end)

  describe("exchange()", function()
    it("returns this plugin's protocol version and capabilities", function()
      local result = handshake.exchange("0.1.0", {}, 7)
      assert.is_string(result.version)
      assert.is_table(result.capabilities)
      assert.is_true(#result.capabilities > 0)
    end)

    it("records the pi channel id passed in", function()
      handshake.exchange("0.1.0", {}, 17)
      assert.is_true(rpc.is_attached())
    end)

    it("treats a nil channel id as a no-op for the channel", function()
      handshake.exchange("0.1.0", {}, nil)
      assert.is_false(rpc.is_attached())
    end)
  end)

  describe("pi_has()", function()
    it("returns false when no peer has been recorded", function()
      assert.is_false(handshake.pi_has("anything"))
    end)

    it("returns true for capabilities the peer advertised", function()
      handshake.exchange("0.1.0", { "pi.session.get" }, 1)
      assert.is_true(handshake.pi_has("pi.session.get"))
    end)

    it("returns false for capabilities the peer did not advertise", function()
      handshake.exchange("0.1.0", { "pi.session.get" }, 1)
      assert.is_false(handshake.pi_has("pi.tool.invoke"))
    end)
  end)
end)
